FROM python:3.9

WORKDIR /app

# Copie o diretório src para o contêiner
COPY . /app

# Instale as dependências
COPY requirements.txt .
RUN pip install -r requirements.txt

# Comando para iniciar sua aplicação
CMD ["python", "/app/__init__.py"]
